Mvc/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic;
using DataModel;

namespace Mvc.Controllers
{
    public class PostController : Controller
    {
        private BusinessDbContext dataDb;
        private CommonService _commonService;
        private UserService _userService;
        private AdminService _adminService;

        public PostController(BusinessDbContext businessDbContext, CommonService commonService, UserService userService, AdminService adminService)
        {
            dataDb = businessDbContext;
            _commonService = commonService;
            _userService = userService;
            _adminService = adminService;

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AdminCreatePost()
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                ViewBag.Users = _adminService.ListUsers(adminId);
                ViewBag.Areas = _adminService.ListAllAreas(adminId);
                ViewBag.Locales = _adminService.ListAllLocales(adminId);
                ViewBag.Categories = _adminService.ListAllCategories(adminId);
                ViewBag.Subcategories = _adminService.ListAllSubcategories(adminId);
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult AdminCreatePost(Post model)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(adminId))
                {
                    Outcome response = _adminService.CreatePost(adminId, 
                                                               model.Title, 
                                                               model.Body, 
                                                               model.OwnerId, 
                                                               model.AreaId, 
                                                               model.LocaleId,
                                                               model.CategoryId,
                                                               model.SubcategoryId);
                    if (response.fail)
                    {
                        ViewBag.ErrorMessage = response.Message();
                        return View("AccessDenied");
                    }
                    return RedirectToAction("KeywordSearch", "CategorySubCategory", new
                    {
                        area = TempData["AreaSlug"],
                        locale = TempData["LocaleSlug"],
                        category = TempData["CategorySlug"],
                        subcategory = TempData["SubCategorySlug"]
                    });
                }
            }
            return View();
        }


        [HttpGet]
        public IActionResult AdminEditPost(int? id)
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                Post post = _commonService.GetPostById(id);


                ViewBag.Users = _adminService.ListUsers(adminId);
                ViewBag.Areas = _adminService.ListAllAreas(adminId);
                ViewBag.Locales = _adminService.ListAllLocales(adminId);
                ViewBag.Categories = _adminService.ListAllCategories(adminId);
                ViewBag.Subcategories = _adminService.ListAllSubcategories(adminId);

                //Dropdown box starting indexes 
                ViewBag.UserId = post.OwnerId;
                ViewBag.AreaId = post.AreaId;
                ViewBag.CategoryId = post.CategoryId;
                ViewBag.LocaleId = post.Locale;
                ViewBag.SubcategoryId = post.SubcategoryId;



                return View(post);
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult AdminEditPost(Post model)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(adminId))
                {
                    Outcome response = _adminService.ModifyPost(adminId,
                                                               model.Id,
                                                               model.Title,
                                                               model.Body,
                                                               model.OwnerId,
                                                               model.AreaId,
                                                               model.LocaleId,
                                                               model.CategoryId,
                                                               model.SubcategoryId);
                    if (response.fail)
                    {
                        ViewBag.ErrorMessage = response.Message();
                        return View("AccessDenied");
                    }
                    return RedirectToAction("KeywordSearch", "CategorySubCategory", new
                    {
                        area = TempData["AreaSlug"],
                        locale = TempData["LocaleSlug"],
                        category = TempData["CategorySlug"],
                        subcategory = TempData["SubCategorySlug"]
                    });
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult PostInformation(int id)
        {
            Post post = _commonService.GetPostById(id);
            return View(post);
        }

        [HttpGet]
        public IActionResult AllPosts()
        {
            TempData.Keep();
            if (User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(adminId))
                {
                    return View(_adminService.ListPosts(adminId));
                }
                return RedirectToAction("KeywordSearch", "CategorySubCategory", new
                {
                    area = TempData["AreaSlug"],
                    locale = TempData["LocaleSlug"],
                    category = TempData["CategorySlug"],
                    subcategory = TempData["SubCategorySlug"]
                });
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult CreatePost()
        {
            if (User.Identity.IsAuthenticated)
            {
                string areaName;
                string categoryName;
                int areaId = -1;
                int categoryId = -1;
                if (TempData["AreaSlug"] != null )
                {
                    areaName = TempData["AreaSlug"].ToString();
                    areaName = _commonService.RemoveSlug(areaName);
                    areaId = _commonService.AreaNameToId(areaName);
                    ViewBag.AreaId = areaId;
                }
                if (TempData["CategorySlug"] != null)
                {
                    categoryName = TempData["CategorySlug"].ToString();
                    categoryName = _commonService.RemoveSlug(categoryName);
                    categoryId = _commonService.CategoryNameToId(categoryName);
                    ViewBag.CategoryId = categoryId;
                }
                ViewBag.Areas = _commonService.ListAreas();
                if (areaId > -1)
                {
                    ViewBag.Locales = _commonService.ListLocales(areaId);
                }
                ViewBag.Categories = _commonService.ListCategories();
                if (categoryId > -1)
                {
                    ViewBag.Subcategories = _commonService.ListSubcategories(categoryId);
                }

                TempData["OwnerId"] = _commonService.UserNameToId(User.Identity.Name);
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult CreatePost(Post model)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string userId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(userId))
                {
                    return RedirectToAction("AdminCreatePost");
                }
                Outcome response =_userService.CreatePost(model.Title, model.Body, userId, 
                    model.AreaId, model.LocaleId, model.CategoryId, model.SubcategoryId);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return RedirectToAction("MyPosts");
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult EditPost(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Post post = _commonService.GetPostById(id);

                string areaName;
                string categoryName;
                ViewBag.OwnerId = post.OwnerId;
                int areaId = post.AreaId;
                int categoryId = post.CategoryId;
                if (TempData["AreaSlug"] != null)
                {
                    areaName = TempData["AreaSlug"].ToString();
                    areaName = _commonService.RemoveSlug(areaName);

Mvc/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessLogic;
using Mvc.Models;
using DataModel;
using Mvc.Data;

namespace Mvc.Controllers
{
    public class UsersController : Controller
    {
        private readonly BusinessDbContext _businessContext;
        private readonly ApplicationDbContext _context;
        private readonly UserService _userService;
        private readonly AdminService _adminService;
        private readonly CommonService _commonService;

        public UsersController(ApplicationDbContext appContext, BusinessDbContext busiContext, UserService userService, AdminService adminService, CommonService commonService)
        {
            _context = appContext;
            _businessContext = busiContext;
            _userService = userService;
            _adminService = adminService;
            _commonService = commonService;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            List<AdminUserViewModel> avms = new List<AdminUserViewModel>();
            foreach (ApplicationUser user in await _context.Users.ToListAsync())
            {
                Models.AccountViewModels.RegisterViewModel rgvm = new Models.AccountViewModels.RegisterViewModel { Email = user.Email };
                AdminUserViewModel adminUserView = new AdminUserViewModel {
                    user = _commonService.GetUser(user.Id),
                    registerViewModel = rgvm
                };
                avms.Add(adminUserView);
            }
            return View(avms);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AdminUserViewModel AuViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(AuViewModel.user);
                await _context.SaveChangesAsync();
                _commonService.CreateUser(AuViewModel.user.Id, AuViewModel.user.Name);
                return RedirectToAction(nameof(Index));
            }
            return View(AuViewModel);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> PromoteUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            User user = _commonService.GetUser(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("PromoteUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PromoteUserConfirmed(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                Outcome result = _adminService.PromoteUser(adminId, id);
                if (result.fail)
                {
                    ViewBag.ErrorMessage = result.Message();
                    return View("AccessDenied");
                }
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(id))
                {
                    return NotFound();
                }
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BobList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/png"  href="@Url.Content("~/favicon-16x16.png")" />
    <style>
        a {
            color: chocolate;
            opacity: 0.7;
            text-decoration: none;
            transition: all 0.6s;
        }

            a:hover {
                opacity: 1;
                text-decoration: none;
                color: cornflowerblue;
            }

        .navbar-header {
            opacity: 0.7;
            transition: all 0.6s;
        }

            .navbar-header:hover {
                opacity: 1.0;
            }

        h2 {
            color: dimgray;
            font-size: 1.2vw;
            transition: all 0.6s;
        }

            h2:hover {
                color: black;
            }
    </style>
</head>
<body>
    <nav id="topbarShared" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="IndexButton" class="navbar-brand">.NET BobList</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
        bool userIsAdmin = TempData["UserIsAdmin"] == null ? false : (bool)TempData["UserIsAdmin"];
        TempData.Keep();
                    }
                    @if (User.Identity.IsAuthenticated)
    {
        if (userIsAdmin)
        {
            TempData.Keep("UserIsAdmin");
                <li><a asp-area="" asp-controller="AreaLocale" asp-action="AreaList">Areas</a></li>
                <li><a asp-area="" asp-controller="AreaLocale" asp-action="LocaleList">Locales</a></li>
                <li><a asp-area="" asp-controller="CategorySubCategory" asp-action="CategoryList">Categories</a></li>
                <li><a asp-area="" asp-controller="CategorySubCategory" asp-action="SubCategoryList">SubCategories</a></li>
                <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                <li><a asp-area="" asp-controller="Post" asp-action="AdminCreatePost">Post</a></li>
                <li><a asp-area="" asp-controller="Post" asp-action="AllPosts">All Posts</a></li>
                <li><a asp-area="" asp-controller="Message" asp-action="Inbox">Inbox</a></li>
                <li><a asp-area="" asp-controller="Message" asp-action="SentMessages">Outbox</a></li>
}
else
{
//TempData.Keep("UserIsAdmin");
                <li><a asp-area="" asp-controller="Post" asp-action="CreatePost">Post</a></li>
                <li><a asp-area="" asp-controller="Post" asp-action="MyPosts">My Posts</a></li>
                <li><a asp-area="" asp-controller="Message" asp-action="Inbox">Inbox</a></li>
                <li><a asp-area="" asp-controller="Message" asp-action="SentMessages">Outbox</a></li>
}
}
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - .NET BobList</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>