Mvc/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic;
using DataModel;

namespace Mvc.Controllers
{
    public class MessageController : Controller
    {
        private BusinessDbContext dataDb;
        private CommonService _commonService;
        private UserService _userService;
        private AdminService _adminService;
        public MessageController(BusinessDbContext businessDbContext, CommonService commonService, UserService userService, AdminService adminService)
        {
            dataDb = businessDbContext;
            _commonService = commonService;
            _userService = userService;
            _adminService = adminService;
        }

        [HttpGet]
        public IActionResult Inbox()
        {
            if (User.Identity.IsAuthenticated)
            {
                string UserId = _commonService.UserNameToId(User.Identity.Name);
                return View(_userService.GetMessagesReceived(UserId));
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult SentMessages()
        {
            if (User.Identity.IsAuthenticated)
            {
                string UserId = _commonService.UserNameToId(User.Identity.Name);
                return View(_userService.GetMessagesSent(UserId));
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult SendMessage(int? id, int? messageId, int? sentBox)
        {
            if (User.Identity.IsAuthenticated)
            {
                string UserId = _commonService.UserNameToId(User.Identity.Name);
                ViewBag.SenderId = UserId;
                Post post = _commonService.GetPostById(id);
                if (post ==null)
                {
                    return View("AccessDenied");
                }
                List<Post> posts = new List<Post>();
                List<User> Recipients = new List<User>();

                posts.Add(post);

                if (messageId == null)
                {
                    Recipients.Add(post.Owner);
                }
                else
                {
                    //To reply to a message
                    Message message = _userService.GetMessageById(messageId);
                    if (sentBox == null)
                    {
                        Recipients.Add(message.Sender);
                    }
                    else
                    {
                        Recipients.Add(message.Receiver);
                    }
                }
                
                ViewBag.Receiver = Recipients;
                ViewBag.Post = posts;
                
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult SendMessage(Message message)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                Outcome response = _userService.CreateMessage(message.PostId, 
                                                              message.SenderId, 
                                                              message.ReceiverId,
                                                              message.Response);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return RedirectToAction("SentMessages");
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult FullMessage(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Message message = _userService.GetMessageById(id);
                return View(message);
            }
            return View("AccessDenied");
        }
    }
}

Mvc/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic;
using DataModel;

namespace Mvc.Controllers
{
    public class PostController : Controller
    {
        private BusinessDbContext dataDb;
        private CommonService _commonService;
        private UserService _userService;
        private AdminService _adminService;

        public PostController(BusinessDbContext businessDbContext, CommonService commonService, UserService userService, AdminService adminService)
        {
            dataDb = businessDbContext;
            _commonService = commonService;
            _userService = userService;
            _adminService = adminService;

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AdminCreatePost()
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                ViewBag.Users = _adminService.ListUsers(adminId);
                ViewBag.Areas = _adminService.ListAllAreas(adminId);
                ViewBag.Locales = _adminService.ListAllLocales(adminId);
                ViewBag.Categories = _adminService.ListAllCategories(adminId);
                ViewBag.Subcategories = _adminService.ListAllSubcategories(adminId);
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult AdminCreatePost(Post model)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(adminId))
                {
                    Outcome response = _adminService.CreatePost(adminId, 
                                                               model.Title, 
                                                               model.Body, 
                                                               model.OwnerId, 
                                                               model.AreaId, 
                                                               model.LocaleId,
                                                               model.CategoryId,
                                                               model.SubcategoryId);
                    if (response.fail)
                    {
                        ViewBag.ErrorMessage = response.Message();
                        return View("AccessDenied");
                    }
                    return RedirectToAction("KeywordSearch", "CategorySubCategory", new
                    {
                        area = TempData["AreaSlug"],
                        locale = TempData["LocaleSlug"],
                        category = TempData["CategorySlug"],
                        subcategory = TempData["SubCategorySlug"]
                    });
                }
            }
            return View();
        }


        [HttpGet]
        public IActionResult AdminEditPost(int? id)
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                Post post = _commonService.GetPostById(id);


                ViewBag.Users = _adminService.ListUsers(adminId);
                ViewBag.Areas = _adminService.ListAllAreas(adminId);
                ViewBag.Locales = _adminService.ListAllLocales(adminId);
                ViewBag.Categories = _adminService.ListAllCategories(adminId);
                ViewBag.Subcategories = _adminService.ListAllSubcategories(adminId);

                //Dropdown box starting indexes 
                ViewBag.UserId = post.OwnerId;
                ViewBag.AreaId = post.AreaId;
                ViewBag.CategoryId = post.CategoryId;
                ViewBag.LocaleId = post.Locale;
                ViewBag.SubcategoryId = post.SubcategoryId;



                return View(post);
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult AdminEditPost(Post model)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(adminId))
                {
                    Outcome response = _adminService.ModifyPost(adminId,
                                                               model.Id,
                                                               model.Title,
                                                               model.Body,
                                                               model.OwnerId,
                                                               model.AreaId,
                                                               model.LocaleId,
                                                               model.CategoryId,
                                                               model.SubcategoryId);
                    if (response.fail)
                    {
                        ViewBag.ErrorMessage = response.Message();
                        return View("AccessDenied");
                    }
                    return RedirectToAction("KeywordSearch", "CategorySubCategory", new
                    {
                        area = TempData["AreaSlug"],
                        locale = TempData["LocaleSlug"],
                        category = TempData["CategorySlug"],
                        subcategory = TempData["SubCategorySlug"]
                    });
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult PostInformation(int id)
        {
            Post post = _commonService.GetPostById(id);
            return View(post);
        }

        [HttpGet]
        public IActionResult AllPosts()
        {
            TempData.Keep();
            if (User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(adminId))
                {
                    return View(_adminService.ListPosts(adminId));
                }
                return RedirectToAction("KeywordSearch", "CategorySubCategory", new
                {
                    area = TempData["AreaSlug"],
                    locale = TempData["LocaleSlug"],
                    category = TempData["CategorySlug"],
                    subcategory = TempData["SubCategorySlug"]
                });
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult CreatePost()
        {
            if (User.Identity.IsAuthenticated)
            {
                string areaName;
                string categoryName;
                int areaId = -1;
                int categoryId = -1;
                if (TempData["AreaSlug"] != null )
                {
                    areaName = TempData["AreaSlug"].ToString();
                    areaName = _commonService.RemoveSlug(areaName);
                    areaId = _commonService.AreaNameToId(areaName);
                    ViewBag.AreaId = areaId;
                }
                if (TempData["CategorySlug"] != null)
                {
                    categoryName = TempData["CategorySlug"].ToString();
                    categoryName = _commonService.RemoveSlug(categoryName);
                    categoryId = _commonService.CategoryNameToId(categoryName);
                    ViewBag.CategoryId = categoryId;
                }
                ViewBag.Areas = _commonService.ListAreas();
                if (areaId > -1)
                {
                    ViewBag.Locales = _commonService.ListLocales(areaId);
                }
                ViewBag.Categories = _commonService.ListCategories();
                if (categoryId > -1)
                {
                    ViewBag.Subcategories = _commonService.ListSubcategories(categoryId);
                }

                TempData["OwnerId"] = _commonService.UserNameToId(User.Identity.Name);
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        public IActionResult CreatePost(Post model)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string userId = _commonService.UserNameToId(User.Identity.Name);
                if (_adminService.IsAdminValid(userId))
                {
                    return RedirectToAction("AdminCreatePost");
                }
                Outcome response =_userService.CreatePost(model.Title, model.Body, userId, 
                    model.AreaId, model.LocaleId, model.CategoryId, model.SubcategoryId);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return RedirectToAction("MyPosts");
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult EditPost(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Post post = _commonService.GetPostById(id);

                string areaName;
                string categoryName;
                ViewBag.OwnerId = post.OwnerId;
                int areaId = post.AreaId;
                int categoryId = post.CategoryId;
                if (TempData["AreaSlug"] != null)
                {
                    areaName = TempData["AreaSlug"].ToString();
                    areaName = _commonService.RemoveSlug(areaName);

Mvc/Views/Post/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access denied";
}

<header>
    <h2 class="text-danger">@ViewData["Title"]</h2>
    <p class="text-danger">You do not have access to this resource. @ViewBag.ErrorMessage</p>
</header>

Mvc/Views/Post/AdminCreatePost.cshtml
@model DataModel.Post

@{
    ViewData["Title"] = "New Post";
}

<h2>New Post</h2>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AdminCreatePost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class ="form-control" asp-items="@(new SelectList(ViewBag.Users,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="AreaId" class="control-label"></label>
                <select asp-for="AreaId" class ="form-control" asp-items="@(new SelectList(ViewBag.Areas,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="LocaleId" class="control-label"></label>
                <select asp-for="LocaleId" class ="form-control" asp-items="@(new SelectList(ViewBag.Locales,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="SubcategoryId" class="control-label"></label>
                <select asp-for="SubcategoryId" class ="form-control" asp-items="@(new SelectList(ViewBag.Subcategories,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllPosts">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/Post/AdminEditPost.cshtml
@model DataModel.Post

@{
    ViewData["Title"] = "Edit Post";
}

<h2>Edit Post</h2>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AdminEditPost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="@(new SelectList(ViewBag.Users,"Id","Name", ViewBag.UserId))"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaId" class="control-label"></label>
                <select asp-for="AreaId" class="form-control" asp-items="@(new SelectList(ViewBag.Areas,"Id","Name", ViewBag.AreaId))"></select>
                <span asp-validation-for="AreaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocaleId" class="control-label"></label>
                <select asp-for="LocaleId" class="form-control" asp-items="@(new SelectList(ViewBag.Locales,"Id","Name", ViewBag.LocaleId))"></select>
                <span asp-validation-for="LocaleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name", ViewBag.CategoryId))"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubcategoryId" class="control-label"></label>
                <select asp-for="SubcategoryId" class="form-control" asp-items="@(new SelectList(ViewBag.Subcategories,"Id","Name", ViewBag.SubcategoryId))"></select>
                <span asp-validation-for="SubcategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllPosts">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/Post/AllPosts.cshtml
@model IEnumerable<DataModel.Post>

@{
    ViewData["Title"] = "Posts";
}

<h2>Posts</h2>

<p>
    <a asp-action="AdminCreatePost">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Timestamp)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Expiration)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Body)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Active)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Locale)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subcategory)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Expiration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Locale.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subcategory.Name)
            </td>
            <td>
                @if (item.Expiration > DateTime.Now)
                {
                    <a asp-action="AdminEditPost" asp-route-id="@item.Id">Edit</a> @Html.Raw("|");
                }
                <a asp-action="DeletePost" asp-route-id="@item.Id">Hide</a>
            </td>
        </tr>
}
    </tbody>
</table>

Mvc/Views/Post/CreatePost.cshtml
@model DataModel.Post

@{
    ViewData["Title"] = "New Post";

    TempData.Keep();

}

<h2>Create Post</h2>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="OwnerId" type="hidden" class="form-control" value="@TempData["OwnerId"]" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaId" class="control-label"></label>
                <select asp-for="AreaId" class="form-control" asp-items="@(new SelectList(ViewBag.Areas,"Id","Name"))"
                        onchange="FillLocales()">
                    <option value="">-- Select Area --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="LocaleId" class="control-label"></label>
                <select asp-for="LocaleId" class="form-control" asp-items="@(new SelectList(Enumerable.Empty<SelectListItem>(),"Id","Name"))">
                    <option value="">-- Select Locale --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"
                        onchange="FillSubcategories()">
                    <option value="">-- Select Category --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SubcategoryId" class="control-label"></label>
                <select asp-for="SubcategoryId" class="form-control" asp-items="@(new SelectList(Enumerable.Empty<SelectListItem>(),"Id","Name"))">
                    <option value="">-- Select Subcategory --</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MyPosts">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    // Write your JavaScript code.
    function FillLocales() {
        var areaId = $('#AreaId').val();
        $.ajax({
            url: '/Post/FillLocales/' + areaId,
            type: "GET",
            dataType: "JSON",
            data: { AreaId: areaId },
            success: function (Locales) {
                $("#LocaleId").html(""); // clear before appending new list
                $.each(Locales, function (i, locale) {
                    $("#LocaleId").append(
                        $('<option></option>').val(locale.id).html(locale.name));
                });
            }
        });
    }

    function FillSubcategories() {
        var categoryId = $('#CategoryId').val();
        $.ajax({
            url: '/Post/FillSubcategories/' + categoryId,
            type: "GET",
            dataType: "JSON",
            data: { CategoryId: categoryId },
            success: function (subcategories) {
                $("#SubcategoryId").html(""); // clear before appending new list
                $.each(subcategories, function (i, subcategory) {
                    $("#SubcategoryId").append(
                        $('<option></option>').val(subcategory.id).html(subcategory.name));
                });
            }
        });
    }
</script>
}

Mvc/Views/Post/DeletePost.cshtml
@model DataModel.Post

@{
    ViewData["Title"] = "Delete Post";
    TempData.Keep();
}

<h2>Delete Post</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Expiration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Expiration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Area.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Locale)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Locale.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subcategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subcategory.Name)
        </dd>
    </dl>
    
    <form asp-action="DeletePost">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Mvc/Views/Post/EditPost.cshtml
@model DataModel.Post

@{
    ViewData["Title"] = "Edit Post";
}

<h2>Edit Post</h2>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input asp-for="OwnerId" type="hidden" value="@ViewBag.OwnerId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaId" class="control-label"></label>
                <select asp-for="AreaId" class="form-control" asp-items="@(new SelectList(ViewBag.Areas,"Id","Name", ViewBag.AreaId))"></select>
                <span asp-validation-for="AreaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocaleId" class="control-label"></label>
                <select asp-for="LocaleId" class="form-control" asp-items="@(new SelectList(ViewBag.Locales,"Id","Name", ViewBag.LocaleId))"></select>
                <span asp-validation-for="LocaleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name", ViewBag.CategoryId))"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubcategoryId" class="control-label"></label>
                <select asp-for="SubcategoryId" class="form-control" asp-items="@(new SelectList(ViewBag.Subcategories,"Id","Name", ViewBag.SubcategoryId))"></select>
                <span asp-validation-for="SubcategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MyPosts">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/Post/PostInformation.cshtml
@model Post
@{
    ViewData["Title"] = Model.Title;
}

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2>@Model.Title</h2>
        @Model.Body
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <p>
            @if (User.Identity.IsAuthenticated && User.Identity.Name != Model.Owner.Name)
            {
                <a asp-controller="Message" asp-action="SendMessage" asp-route-id=@Model.Id>Send this Owner a message</a>
            }
        <button onclick="history.go(-1);" class="btn btn-primary">Return to Search</button>
        </p>
    </div>
</div>