Mvc/Controllers/CategorySubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic;
using DataModel;
using X.PagedList;
using Mvc.Models;

namespace Mvc.Controllers
{
    public class CategorySubCategoryController : Controller
    {

        private BusinessDbContext dataDb;
        private readonly AdminService _adminService;
        private readonly CommonService _commonService;
        private readonly UserService _userService;

        public CategorySubCategoryController(BusinessDbContext businessDbContext, AdminService adminService)
        {
            dataDb = businessDbContext;
            _adminService = adminService;
            _commonService = new CommonService(dataDb);
            _userService = new UserService(dataDb);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult KeywordSearch(string area, string locale, string category, string subcategory,
                                             string currentFilter, int? page)
        {
            ViewBag.AreaSlug = area;
            ViewBag.LocaleSlug = locale;
            ViewBag.CategorySlug = category;
            ViewBag.SubCategorySlug = subcategory;

            TempData["AreaSlug"] = area;
            TempData["LocaleSlug"] = locale;
            TempData["CategorySlug"] = category;
            TempData["SubCategorySlug"] = subcategory;
            TempData.Keep();

            List<Post> keywordPosts;
            Category categoryFilter = _commonService.GetCategoryFromSlug(category);
            Subcategory subcategoryFilter = _commonService.GetSubcategoryFromSlug(subcategory);
            Area areaFilter = _commonService.GetAreaFromSlug(area);
            Locale localeFilter = _commonService.GetLocaleFromSlug(locale);
            int categoryFilterId = -1, subcategoryFilterId = -1, areaFilterId = -1, localeFilterId = -1;
            if (categoryFilter != null)
            {
                categoryFilterId = categoryFilter.Id;
            }
            if (subcategoryFilter != null)
            {
                subcategoryFilterId = subcategoryFilter.Id;
            }
            if (areaFilter != null)
            {
                areaFilterId = areaFilter.Id;
            }
            if (localeFilter != null)
            {
                localeFilterId = localeFilter.Id;
            }
            currentFilter = String.IsNullOrEmpty(currentFilter) ? "" : currentFilter;
            keywordPosts = _userService.FilterPosts(_userService.SearchPostsByKeywords(currentFilter), 
                categoryFilterId, subcategoryFilterId, areaFilterId, localeFilterId);
            int pageNumber = page ?? 1;
            ViewBag.Posts = keywordPosts.ToPagedList(pageNumber, 10);
            ViewBag.CurrentFilter = currentFilter;
            ViewBag.Page = pageNumber;
            return View("KeywordSearch");
        }

        [HttpGet]
        public IActionResult CategoryCreate()
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CategoryCreate(Category model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("AccessDenied");
            }
            if (ModelState.IsValid)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                Outcome response = _adminService.CreateCategory(adminId, model.Name);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return RedirectToAction("CategoryList");
            }
            return View();
        }

        [HttpGet]
        public IActionResult SubCategoryCreate()
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                ViewBag.Categories = _commonService.ListUnhiddenCategories();
                return View();
            }
            return View("AccessDenied");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubCategoryCreate(AdminUserViewModel model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("AccessDenied");
            }
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                Outcome response = _adminService.CreateSubcategory(adminId, model.subcategory.Name, model.subcategory.CategoryId);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return RedirectToAction("SubCategoryList");
            }
            return View();
        }

        public IActionResult CategoryList()
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                List<Category> categories = dataDb.Categories.Where(a => !a.Hidden).ToList();
                return View(_commonService.ListUnhiddenCategories());
            }
            return View("AccessDenied");
        }

        public IActionResult SubCategoryList()
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                return View(_adminService.ListAllSubcategories(adminId));
            }
            return View("AccessDenied");
        }

        public IActionResult DetailsCategory(int? id)
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                if (id == null)
                {
                    return StatusCode(400);
                }
                Category category = _commonService.GetCategory((int)id);
                if (category == null)
                {
                    return NotFound();
                }
                ViewBag.CategorySubcategories = _commonService.ListSubcategories((int)id);
                return View(category);
            }
            return View("AccessDenied");
        }

        [HttpGet]
        public IActionResult CategoryEdit(int? id)
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                if (id == null)
                {
                    return StatusCode(400);
                }
                Category category = _commonService.GetCategory((int)id);
                return View(category);
            }
            return View("AccessDenied");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CategoryEdit(Category model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("AccessDenied");
            }
            if (ModelState.IsValid)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                Outcome response = _adminService.ModifyCategory(adminId, model.Id, model.Name);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return View("CategoryList");
            }
            return View();
        }

        [HttpGet]
        public IActionResult SubCategoryEdit(int? id)
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                if (id == null)
                {
                    return StatusCode(400);
                }
                ViewBag.Categories = _commonService.ListUnhiddenCategories();
                return View(_commonService.GetSubcategory((int)id));
            }
            return View("AccessDenied");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubCategoryEdit(AdminUserViewModel model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("AccessDenied");
            }
            if (ModelState.IsValid)
            {
                string adminId = _commonService.UserNameToId(User.Identity.Name);
                Outcome response = _adminService.ModifySubcategory(adminId, 
                    model.subcategory.Id, model.subcategory.Name, model.category.Id);
                if (response.fail)
                {
                    ViewBag.ErrorMessage = response.Message();
                    return View("AccessDenied");
                }
                return View("SubCategoryList");
            }
            return View();
        }

        [HttpGet]
        public IActionResult CategoryDelete(int? id)
        {
            string adminId = _commonService.UserNameToId(User.Identity.Name);
            if (User.Identity.IsAuthenticated && _adminService.IsAdminValid(adminId))
            {
                if (id == null)
                {

Mvc/Views/AreaLocale/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access denied";
}

<header>
    <h2 class="text-danger">@ViewData["Title"]</h2>
    <p class="text-danger">You do not have access to this resource. @ViewBag.ErrorMessage</p>
</header>

Mvc/Views/AreaLocale/AreaCreate.cshtml
@model DataModel.Area

@{
    ViewData["Title"] = "Create Area";
}

<h2>Create New Area</h2>

<h4>Area</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AreaCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AreaList">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/AreaLocale/AreaDelete.cshtml
@model DataModel.Area

@{
    ViewData["Title"] = "Delete Area";
}

<h2>Delete Area</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Area</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="AreaDelete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="AreaList">Back to List</a>
    </form>
</div>

Mvc/Views/AreaLocale/AreaEdit.cshtml
@model DataModel.Area

@{
    ViewData["Title"] = "Edit Area";
}

<h2>Edit Area</h2>

<h4>Area</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AreaEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AreaList">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/AreaLocale/AreaList.cshtml
@model IEnumerable<DataModel.Area>

@{
    ViewData["Title"] = "Area List";
}

<h2>Areas</h2>

<p>
    <a asp-action="AreaCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="AreaEdit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="DetailsArea" asp-route-id="@item.Id">Details</a> |
                <a asp-action="AreaDelete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Mvc/Views/AreaLocale/DetailsArea.cshtml
@model DataModel.Area

@{
    ViewData["Title"] = "Area Details";
}

<h2>Area Details</h2>

<div>
    <h4>Area</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (Locale item in ViewBag.AreaLocales)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Area.Name)
                </td>
                <td>
                    <a asp-action="LocaleEdit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="LocaleDelete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

</div>
<div>
    <a asp-action="AreaEdit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="AreaList">Back to List</a>
</div>

Mvc/Views/AreaLocale/Index.cshtml
@{
    ViewData["Title"] = "Select locale";
    TempData.Keep();
}

<div class="row">
    <div class="col-md-3">
        <h1> 
                @Html.Raw(ViewBag.Locale == "" ? ViewBag.Area : ViewBag.Locale)
            </h1>
        <h2>Locale</h2>
        <ul>
            @foreach (Locale item in ViewBag.Locales)
            {
                <li>@Html.ActionLink(item.Name, "Index", new { area = item.Area.GetSlug(), locale = item.GetSlug() })</li>
            }
        </ul>
    </div>
</div> 
<div class="row">
    <div class="col-md-3">
        @foreach (Category catitem in ViewBag.Categories)
        {
        <h2>@Html.ActionLink(catitem.Name, "KeywordSearch", "CategorySubCategory", new { area = ViewBag.AreaSlug, locale = ViewBag.LocaleSlug, Category = catitem.GetSlug() })</h2>
        <ul>
            @foreach (Subcategory subCatItem in catitem.Subcategories)
            {
                <li>@Html.ActionLink(subCatItem.Name, "KeywordSearch", "CategorySubCategory", new { area = ViewBag.AreaSlug, locale = ViewBag.LocaleSlug, Category = subCatItem.Category.GetSlug(), Subcategory = subCatItem.GetSlug() })</li>
            }
        </ul>
        }
    </div>
</div>

Mvc/Views/AreaLocale/LocaleCreate.cshtml
@model AdminUserViewModel

@{
    ViewData["Title"] = "Create Locale";
}

<h2>Create New Locale</h2>

<h4>Locale</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="LocaleCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.locale.Name" class="control-label"></label>
                <input asp-for="@Model.locale.Name" class="form-control" />
                <span asp-validation-for="@Model.locale.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.locale.Area" class="control-label"></label>
                <select asp-for="@Model.locale.AreaId" class ="form-control" asp-items="@(new SelectList(ViewBag.Areas,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="LocaleList">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/AreaLocale/LocaleDelete.cshtml
@model DataModel.Locale

@{
    ViewData["Title"] = "Delete Locale";
}

<h2>Delete Locale</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Locale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Area.Name)
        </dd>
    </dl>
    
    <form asp-action="LocaleDelete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="LocaleList">Back to List</a>
    </form>
</div>

Mvc/Views/AreaLocale/LocaleEdit.cshtml
@model DataModel.Locale

@{
    ViewData["Title"] = "Edit Locale";
}

<h2>Edit Locale</h2>

<h4>Locale</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="LocaleEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <select asp-for="Area" class="form-control" asp-items="@(new SelectList(ViewBag.Areas,"Id","Name"))"></select>
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="LocaleList">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc/Views/AreaLocale/LocaleList.cshtml
@model IEnumerable<DataModel.Locale>

@{
    ViewData["Title"] = "Locales List";
}

<h2>Locales</h2>

<p>
    <a asp-action="LocaleCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area.Name)
            </td>
            <td>
                <a asp-action="LocaleEdit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="LocaleDelete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>